### ISSUE TITLE
any chance to get rid of error 403?

### ISSUE THREAD

**Issue by smx06** [gdrive-org/gdrive#424] opened 2019-01-28 13:23 UTC
As someone mentioned error 403 is related to built-in client ID quotas. Is it true?
Is there any way to put this id in config file? It could be very useful.
Also it will be good to have a smallest tutorial of how to create this ID in google console (with activating APIs, etc.) cause it is not clear (see coments here https://github.com/prasmussen/gdrive/issues/392)
The more users will use the app, the more errors will appear. At some moment the app will become very unstable..

**Comment by jollybully** [comment] 2019-01-28 13:35
this would be great - i've been getting 403's all morning today.

**Comment by jollybully** [comment] 2019-01-28 15:08
enable the drive api in google dev console
create OAuth 2.0 client ID (type UI/other)  - retrieve the clientID & secret
updated clientID & secret in handlers_drive.go
recompile
remove previous credentials ~/.gdrive/token_v2.json
re-authenticate - gdrive about etc...

**Comment by mbenlioglu** [comment] 2019-03-11 15:50
Available workaround described in #426. Possible solutions will be investigated.
Duplicate of #392

**Closed by mbenlioglu** 2019-03-11 15:50 UTC
Labels: duplicate
