### ISSUE TITLE
50% failure rate to gather info with  gdrive info <url> | grep Modified

### ISSUE THREAD

**Issue by DaveFurbag** [gdrive-org/gdrive#445] opened 2019-03-21 10:20 UTC
While the info command seems to have a 100% success rate, however when using grep to return just one line of the results it fails to give any result about 50% of the time.  Weird, eh.

The help for grive info doesn't make sense for the info subcommand, or I'm expecting different detail from it.

**Comment by mbenlioglu** [comment] 2019-03-26 14:26
It's most likely caused by API limit issue that currently everyone experiencing. Check #426 for workaround for API limits, until we introduce an official fix

**Comment by mbenlioglu** [comment] 2019-03-27 13:51
Can you confirm whether it's related to API limit issue?

**Comment by mbenlioglu** [comment] 2019-04-08 15:38
Closing, reopen if you have followup.

**Closed by mbenlioglu** 2019-04-08 15:38 UTC
Labels: awaiting followup
