### ISSUE TITLE
Command line binary not working for MacOS Mojave

### ISSUE THREAD

**Issue by forrie** [gdrive-org/gdrive#456] opened 2019-04-17 18:45 UTC
The posted binary for 64bit Mac does not work on MacOS Mojave.  See error log below.

`bash-5.0# ./gdrive
failed MSpanList_Insert 0x838000 0x406b837364e38 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x566980, 0x10)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0x7ffeefbff5e0 sp=0x7ffeefbff5c8
runtime.(*mSpanList).insert(0x77e4a8, 0x838000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:933 +0x293 fp=0x7ffeefbff610 sp=0x7ffeefbff5e0
runtime.(*mheap).freeSpanLocked(0x77dca0, 0x838000, 0x100, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:809 +0x4be fp=0x7ffeefbff678 sp=0x7ffeefbff610
runtime.(*mheap).grow(0x77dca0, 0x8, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:675 +0x2a0 fp=0x7ffeefbff6d0 sp=0x7ffeefbff678
runtime.(*mheap).allocSpanLocked(0x77dca0, 0x1, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:553 +0x4e3 fp=0x7ffeefbff728 sp=0x7ffeefbff6d0
runtime.(*mheap).alloc_m(0x77dca0, 0x1, 0x15, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:437 +0x119 fp=0x7ffeefbff758 sp=0x7ffeefbff728
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:502 +0x41 fp=0x7ffeefbff788 sp=0x7ffeefbff758
runtime.systemstack(0x7ffeefbff7a8)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff790 sp=0x7ffeefbff788
runtime.(*mheap).alloc(0x77dca0, 0x1, 0x10000000015, 0x2dc6f)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mheap.go:503 +0x63 fp=0x7ffeefbff7d8 sp=0x7ffeefbff790
runtime.(*mcentral).grow(0x77f8a0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcentral.go:209 +0x93 fp=0x7ffeefbff840 sp=0x7ffeefbff7d8
runtime.(*mcentral).cacheSpan(0x77f8a0, 0x778788)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcentral.go:89 +0x47d fp=0x7ffeefbff880 sp=0x7ffeefbff840
runtime.(*mcache).refill(0x834000, 0x15, 0x7ffeefbff8e8)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/mcache.go:119 +0xcc fp=0x7ffeefbff8b8 sp=0x7ffeefbff880
runtime.mallocgc.func2()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:642 +0x2b fp=0x7ffeefbff8d8 sp=0x7ffeefbff8b8
runtime.systemstack(0x7ffeefbff978)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:307 +0xab fp=0x7ffeefbff8e0 sp=0x7ffeefbff8d8
runtime.mallocgc(0x180, 0x50b7c0, 0x0, 0x800000000)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:643 +0x869 fp=0x7ffeefbff9b8 sp=0x7ffeefbff8e0
runtime.newobject(0x50b7c0, 0x778bd0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/malloc.go:781 +0x42 fp=0x7ffeefbff9e0 sp=0x7ffeefbff9b8
runtime.malg(0x8000, 0x778f80)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:2634 +0x27 fp=0x7ffeefbffa18 sp=0x7ffeefbff9e0
runtime.mpreinit(0x779520)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/os1_darwin.go:140 +0x1f fp=0x7ffeefbffa30 sp=0x7ffeefbffa18
runtime.mcommoninit(0x779520)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:494 +0x105 fp=0x7ffeefbffa78 sp=0x7ffeefbffa30
runtime.schedinit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:434 +0x79 fp=0x7ffeefbffac0 sp=0x7ffeefbffa78
runtime.rt0_go(0x7ffeefbffaf8, 0x1, 0x7ffeefbffaf8, 0x0, 0x0, 0x1, 0x7ffeefbffc28, 0x0, 0x7ffeefbffc31, 0x7ffeefbffc3f, ...)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:138 +0x132 fp=0x7ffeefbffac8 sp=0x7ffeefbffac0`

**Comment by mbenlioglu** [comment] 2019-04-19 16:38
Duplicate of #450

**Closed by mbenlioglu** 2019-04-19 16:38 UTC
Labels: duplicate
