### ISSUE TITLE
Failed to get file: googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded

### ISSUE THREAD

**Issue by msnoon** [gdrive-org/gdrive#438] opened 2019-02-27 23:05 UTC
I am trying to download data using this command but it fails with the error in subject line.

 ~/gdrive-linux-x64 download --recursive 1nVSPhzhujEXNaLR86daW0ioCUFNzKOX3

How can I download data on HPC from google drive. gdrive worked for me a couple of months ago but not any more. any help would be appreciated.

**Comment by ThomasAllan** [comment] 2019-02-28 12:21
Sounds like the token may have expired. 

Find the .gdrive folder in the home directory and delete `token_v2.json`. You can also find this file by running `dir token_v2.json /s` in a command prompt. 

Once deleted run `gdrive list` which will prompt you to set up a new token.

**Comment by atillay** [comment] 2019-03-01 08:33
I wonder if it is not a limit of the client app : https://github.com/prasmussen/gdrive/blob/master/handlers_drive.go#L17
 
I was able to rebuild the binary with my own client id :
- Clone the github project
- Go to https://console.cloud.google.com/apis/credentials/oauthclient
- Create an "Other" Oauth client ID
- Replace with your credentials in : https://github.com/prasmussen/gdrive/blob/master/handlers_drive.go#L17
- Install Golang : https://golang.org/dl/
- Run go get github.com/prasmussen/gdrive
- Go to the folder where the project is cloned and run ```./_release/build-all.sh```
- Retrieve the generated binary in ```./_release/bin```

**Comment by tripLr** [comment] 2019-03-01 17:56
This api is overused, creat your own or wrap gdrive 
bash command with
while ! gdrive upload --parent ________; do sleep 1; done

Please see my fork so I can help maintain

**Comment by msnoon** [comment] 2019-03-01 18:17
@tripLr, How to create my own or wrap? I have tried @ThomasAllan suggestion it doesn't work. and I dont understand what's suggested in #426 or @atillay suggested! have no clue about these things!

**Comment by hikenshi** [comment] 2019-03-03 15:30
@tripLr 
Thank you, it is working now.
@msnoon:
Please read this: https://github.com/tripLr/gdrive/blob/master/TUTORIAL-INSTALL-Windows
with the linux, just clone the github, then edit "handlers_drive.go" with your "Credentials" which created by "TUTORIAL-INSTALL-Windows"

**Comment by mbenlioglu** [comment] 2019-03-11 15:49
Available workaround described in #426. Possible solutions will be investigated.

Duplicate of #392

**Closed by mbenlioglu** 2019-03-11 15:49 UTC
Labels: bug, duplicate, investigating, workaround available

**Comment by grandeto** [comment] 2019-03-12 21:19
Rebuild the repo with your own credentials.
Tested on Ubuntu 16.04

**use sudo if needed on your enviroment

apt-get install git
apt-get update
apt install software-properties-common
add-apt-repository ppa:git-core/ppa # apt update; apt install git
// Install go
wget https://dl.google.com/go/go1.12.linux-amd64.tar.gz
mv go1.12.linux-amd64.tar.gz /usr/local/
cd /usr/local
tar -zxvf go1.12.linux-amd64.tar.gz
cd ~
nano .profile
// Add these global variables as follow at the end of the file:
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
// Update current shell session:
source ~/.profile
// Check go version
go version
// Login to google developers and create a new project. Give it name for instance Gdrive-my-project 
https://console.developers.google.com/apis/dashboard
// Go to google drive api and enable it. Then click on Credentials
https://console.developers.google.com/apis/library/drive.googleapis.com
// From dropdown choose Other UI and check User data
// Then click on "What credentials do I need?"
// Give again same name Gdrive-my-project and save
// If old gdrive installation exists:
cd ~
rm -r gdrive
rm -r .gdrive
rm /usr/local/bin/gdrive
// Get the repo
go get github.com/gdrive-org/gdrive
cd go/src/github.com/gdrive-org/gdrive/
nano handlers_drive.go
// On line 17 and 18 change the credentials (ClientId and ClientSecret) with those created in google drive api
// Compile the executable by run ‘go build’ in go/src/github.com/gdrive-org/gdrive/
go build
install gdrive /usr/local/bin/gdrive
install gdrive ~/go/bin/gdrive
// Run some gdrive command to setup the gdrive permissions
gdrive about
