### ISSUE TITLE
How can do fast upload for 600 file

### ISSUE THREAD

**Issue by ahmtxonly** [gdrive-org/gdrive#471] opened 2019-07-03 13:19 UTC
Hello,

I am trying to upload 600 file to gdrive but it takes too much time to upload, is there any way to do it faster?

**Comment by mbenlioglu** [comment] 2019-07-04 15:48
Unless your bandwidth is low, the slowness is most likely caused by sending individual queries to the Drive for each file. Batch queries are not added in this version. It'll be added in the next release.

**Comment by mbenlioglu** [comment] 2019-07-04 15:51
Closing as adding batch query support is already mentioned. #381

**Closed by mbenlioglu** 2019-07-04 15:51 UTC
