### ISSUE TITLE
Download link gdrive-linux-x64 is not found

### ISSUE THREAD

**Issue by weakiwi** [gdrive-org/gdrive#482] opened 2019-07-26 03:14 UTC
response 404 not found

**Comment by PaschalisSk** [comment] 2019-07-26 06:05
#479, you can get the [old one](https://github.com/gdrive-org/gdrive/issues/479#issuecomment-515259713).

**Comment by mbenlioglu** [comment] 2019-07-29 02:42
Duplicate of #479

**Closed by mbenlioglu** 2019-07-29 02:42 UTC
